// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Gauge struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Target      float64        `json:"target"`
	Unit        string         `json:"unit"`
	Icon        string         `json:"icon"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type GaugeValue struct {
	ID      int64     `json:"id"`
	GaugeID int64     `json:"gauge_id"`
	Value   float64   `json:"value"`
	Date    time.Time `json:"date"`
}
