// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateGaugeInstance(ctx context.Context, arg CreateGaugeInstanceParams) (GaugeInstance, error)
	CreateGaugeTemplate(ctx context.Context, arg CreateGaugeTemplateParams) (GaugeTemplate, error)
	CreateGaugeValue(ctx context.Context, arg CreateGaugeValueParams) error
	DeleteGaugeInstance(ctx context.Context, id int64) error
	DeleteGaugeTemplate(ctx context.Context, id int64) error
	GetCurrentValue(ctx context.Context, gaugeID int64) (int64, error)
	// Get historical data for a specific gauge instance (grouped by month)
	// Note: For template-level historical data, use GetGaugeHistoryByTemplate instead
	GetGaugeHistory(ctx context.Context, gaugeID int64) ([]GetGaugeHistoryRow, error)
	// Get historical data for a gauge template grouped by time periods based on frequency
	// Returns one row per gauge instance (period) with aggregated values
	GetGaugeHistoryByTemplate(ctx context.Context, id int64) ([]GetGaugeHistoryByTemplateRow, error)
	// Gauge Instances CRUD Operations
	GetGaugeInstance(ctx context.Context, id int64) (GaugeInstance, error)
	// Gauge Templates CRUD Operations
	GetGaugeTemplate(ctx context.Context, id int64) (GaugeTemplate, error)
	GetGaugeValues(ctx context.Context, gaugeID int64) ([]GaugeValue, error)
	InstanceExistsForPeriod(ctx context.Context, arg InstanceExistsForPeriodParams) (int64, error)
	ListActiveGaugeTemplates(ctx context.Context) ([]GaugeTemplate, error)
	// Dashboard and Current Period Queries
	ListCurrentPeriodGaugeInstances(ctx context.Context, arg ListCurrentPeriodGaugeInstancesParams) ([]ListCurrentPeriodGaugeInstancesRow, error)
	ListGaugeInstances(ctx context.Context) ([]GaugeInstance, error)
	ListGaugeInstancesByTemplate(ctx context.Context, templateID int64) ([]GaugeInstance, error)
	ListGaugeTemplates(ctx context.Context) ([]GaugeTemplate, error)
	UpdateGaugeInstanceValue(ctx context.Context, arg UpdateGaugeInstanceValueParams) error
	UpdateGaugeTemplate(ctx context.Context, arg UpdateGaugeTemplateParams) error
}

var _ Querier = (*Queries)(nil)
