// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateGauge(ctx context.Context, arg CreateGaugeParams) (Gauge, error)
	CreateGaugeValue(ctx context.Context, arg CreateGaugeValueParams) error
	DeleteGauge(ctx context.Context, id int64) error
	GetCurrentValue(ctx context.Context, gaugeID int64) (float64, error)
	GetGauge(ctx context.Context, id int64) (Gauge, error)
	GetGaugeHistory(ctx context.Context, gaugeID int64) ([]GetGaugeHistoryRow, error)
	ListGauges(ctx context.Context) ([]Gauge, error)
	UpdateGauge(ctx context.Context, arg UpdateGaugeParams) error
}

var _ Querier = (*Queries)(nil)
