DROP TABLE IF EXISTS gauge_values;
DROP TABLE IF EXISTS gauges;

CREATE TABLE gauges (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT,
    target REAL NOT NULL,
    value REAL NOT NULL DEFAULT 0,
    unit TEXT NOT NULL,
    icon TEXT NOT NULL DEFAULT 'chart-bar',
    frequency TEXT NOT NULL DEFAULT 'monthly',
    direction TEXT NOT NULL DEFAULT 'under',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE gauge_values (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    gauge_id INTEGER NOT NULL,
    value REAL NOT NULL,
    date DATETIME NOT NULL,
    FOREIGN KEY (gauge_id) REFERENCES gauges(id) ON DELETE CASCADE
);
